### ISSUE TITLE
.net core host force close

### ISSUE THREAD

**Issue by Hamid-Najafi** [freepvps/mtproto-proxy#3]
can anyone tell me that what is the cause of this happening?
(vm? , worked fine for one week)
![2018-07-23_06-56-11](https://user-images.githubusercontent.com/17290304/43054241-d5f72838-8e45-11e8-8c1e-8a11452cddf4.png)

**Comment by Goldenstarc** [comment]
Another bug

```
System.ObjectDisposedException: Cannot access a disposed object.

Object name: 'System.Net.Sockets.Socket'.

at System.Net.Sockets.Socket.get_RemoteEndPoint()

at tgsocks.Program.ProcessConnectionEvent(ConnectionTable connectionTable, Pr

oxyConnection connection, String eventMessage) in C:\MTProto Proxy\Source\mtprot

o-proxy\src\tgsocks\Program.cs:line 78 
at MTProto.Proxy.ConnectionTable.Register(ProxyConnection connection) in C:\M

TProto Proxy\Source\mtproto-proxy\src\MTProto\Proxy\ConnectionTable.cs:line 25

at MTProto.Proxy.SocketServer.ProcessAccepted(Socket socket) in C:\MTProto Pr 
oxy\Source\mtproto-proxy\src\MTProto\Proxy\SocketServer.cs:line 69

at MTProto.Proxy.SocketServer.OnSocketAccept(IAsyncResult result) in C:\MTPro 
to Proxy\Source\mtproto-proxy\src\MTProto\Proxy\SocketServer.cs:line 103

at System.Net.LazyAsyncResult.Complete(IntPtr userToken) 
at System.Net.ContextAwareResult.CompleteCallback()

at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s) 
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo

ntext, ContextCallback callback, Object state) 
--- End of stack trace from previous location where exception was thrown ---

at System.Net.ContextAwareResult.Complete(IntPtr userToken) 
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr u

serToken) 
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numB 
ytes, SocketError socketError)

at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 
errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)

at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 
errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by Arashz22** [comment]
> can anyone tell me that what is the cause of this happening?
> (vm? , worked fine for one week)
> ![2018-07-23_06-56-11](https://user-images.githubusercontent.com/17290304/43054241-d5f72838-8e45-11e8-8c1e-8a11452cddf4.png)

Too late, but it may happens when the firewall blocks the port, let's add your port to the Inbound and outbound and allow the connections.
